apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-stock-react
  namespace: zineb
  labels:
    app: gestion-stock-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-stock-react
  template:
    metadata:
      labels:
        app: gestion-stock-react
    spec:
      containers:
        - name: gestion-stock-react
          image: gestion-stock-react:latest  # Utilisation de l'image locale
          imagePullPolicy: Never             # Important pour utiliser l'image locale
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-stock-react
  namespace: zineb
spec:
  type: NodePort
  selector:
    app: gestion-stock-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Accessible sur le port 30007 de ta VM
